### ISSUE TITLE
Bug: Complex script is dropped partially

### ISSUE THREAD

**Issue by lentil32** [QuarticCat/zsh-smartcache#1]
### Steps to reproduce:
`hello.zsh`:
```zsh
#!/bin/zsh
function edd () {
    echo "\
    # Hook to add new entries to the database.
    function __zoxide_hook() {
        # shellcheck disable=SC2312
        \command zoxide add -- "$(__zoxide_pwd)"
    }
    "
}
```
In terminal, run:
```console
source hello.zsh; smartcache eval hello
```
Then, cache file is like:
`[md5]`
```zsh
    # Hook to add new entries to the database.
    function __zoxide_hook() {
        # shellcheck disable=SC2312
        

```

### Expected cache file
`[md5]`
```zsh
    # Hook to add new entries to the database.
    function __zoxide_hook() {
        # shellcheck disable=SC2312
         \command zoxide add -- "$(__zoxide_pwd)"
    }


```

**Comment by QuarticCat** [comment]
Hi, sorry for replying so late. I can't see problems in your example since directly invoking `hello` (assuming you mistyped `hello` as `edd`) gives me the incomplete output. However, I still addressed some bugs and pushed a new commit to fix them. Give me another example if the latest commit cannot solve your problem.
